// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.friend.ios.voicecall

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VoiceCallSessionPigeonPigeonUtils {

  fun createConnectionError(channelName: String): VoiceCallSessionPigeonError {
    return VoiceCallSessionPigeonError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is VoiceCallSessionPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class VoiceCallSessionPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class VoiceCallSessionPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * Dart -> native. One telecom call per free-form voice-mode session.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VoiceCallSessionHostApi {
  /**
   * Registers the self-managed PhoneAccount (idempotent) and places the
   * call. Resolves `true` once the Connection is active and the CallStyle
   * foreground service is up; `false` when telecom refuses the call
   * (`isOutgoingCallPermitted` said no — e.g. a real cellular call is
   * already active). The voice mode itself must keep working when this
   * returns `false`: the call shell is UX + background-mic legality, not a
   * prerequisite for audio (fail-open, like every other shell here).
   */
  fun start(sessionId: Long, callback: (Result<Boolean>) -> Unit)
  /**
   * Ends the call: disconnects + destroys the Connection, stops the
   * foreground service, removes the notification. Idempotent; safe for a
   * session that never got a call (start returned false) or already ended.
   */
  fun end(sessionId: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by VoiceCallSessionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VoiceCallSessionPigeonPigeonCodec()
    }
    /** Sets up an instance of `VoiceCallSessionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VoiceCallSessionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_voice_call_session.VoiceCallSessionHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.start(sessionIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCallSessionPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VoiceCallSessionPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_voice_call_session.VoiceCallSessionHostApi.end$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.end(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VoiceCallSessionPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(VoiceCallSessionPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class VoiceCallSessionFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VoiceCallSessionFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      VoiceCallSessionPigeonPigeonCodec()
    }
  }
  /**
   * The call ended natively rather than through [VoiceCallSessionHostApi.end]:
   * the user hit hang-up in the notification, telecom tore the call down
   * (an answered real phone call — session policy is to END, not hold, per
   * Igor's 24.08 decision), or the Connection failed. The Dart side reacts
   * by stopping the whole voice mode (the same path as the chat Stop
   * button); a reason string is carried for logging only.
   */
  fun onEnded(sessionIdArg: Long, reasonArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_voice_call_session.VoiceCallSessionFlutterApi.onEnded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg, reasonArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(VoiceCallSessionPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VoiceCallSessionPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
