// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.friend.ios.voiceplayer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object StreamingPcmPlayerPigeonPigeonUtils {

  fun createConnectionError(channelName: String): StreamingPcmPlayerPigeonError {
    return StreamingPcmPlayerPigeonError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is StreamingPcmPlayerPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class StreamingPcmPlayerPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class StreamingPcmPlayerPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * Dart -> native. One player instance per warm hub session (design doc §4:
 * `VoicePlayerFactory` is called once per `ensureWarm()`); a fresh `start()`
 * after a previous `close()` is a new instance, not a resume.
 *
 * `start(sessionId)` resolves once the AudioTrack is built and playing (silence,
 * nothing enqueued yet) or throws a PlatformException with `track_init_failed` if
 * AudioTrack construction/initialization fails. `sessionId` is a Dart-minted,
 * monotonically increasing identity: every FlutterApi event carries the id of the
 * session it belongs to, and every HostApi call below is dropped natively if
 * `sessionId` does not match the currently active one (guards against a call that
 * raced a `close()`).
 *
 * `enqueuePcm16`/`flush`/`clear` are fire-and-forget (no round trip) — the turn
 * choreography in `hub_session.dart` never awaits them, only `start`/`close`.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface StreamingPcmPlayerHostApi {
  fun start(sessionId: Long, callback: (Result<Unit>) -> Unit)
  /**
   * Raw 16-bit little-endian mono PCM @24kHz (Gemini Live spoken-audio wire
   * format, `geminiHubSession.ts`/`gemini_hub_session.dart` `playAudio`). Queued
   * in arrival order and written to the AudioTrack by a dedicated native thread.
   */
  fun enqueuePcm16(bytes: ByteArray, sessionId: Long)
  /**
   * End of turn (`BaseHubSession.flushPlayback`): this implementation writes
   * straight through with no pre-roll cushion, so nothing is actually withheld —
   * `flush` only arms `onDrained` detection for the audio queued up to this
   * call (see that method's doc for why it is a fixed post-roll estimate, not
   * an exact playback-position marker).
   */
  fun flush(sessionId: Long)
  /**
   * Barge-in (`BaseHubSession.clearPlayback`): drop everything queued AND
   * already handed to the AudioTrack, immediately, then leave the track paused
   * and ready — the next `enqueuePcm16` resumes it for the replacement turn on
   * the same warm player (no `start()` round trip).
   */
  fun clear(sessionId: Long)
  /**
   * Idempotent teardown: stop the writer thread, release the AudioTrack. Safe to
   * call on an already-closed or never-started player.
   */
  fun close(sessionId: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by StreamingPcmPlayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      StreamingPcmPlayerPigeonPigeonCodec()
    }
    /** Sets up an instance of `StreamingPcmPlayerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StreamingPcmPlayerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.start(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StreamingPcmPlayerPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(StreamingPcmPlayerPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerHostApi.enqueuePcm16$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bytesArg = args[0] as ByteArray
            val sessionIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.enqueuePcm16(bytesArg, sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              StreamingPcmPlayerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerHostApi.flush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.flush(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              StreamingPcmPlayerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerHostApi.clear$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.clear(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              StreamingPcmPlayerPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            api.close(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StreamingPcmPlayerPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(StreamingPcmPlayerPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart. Both map straight onto `VoicePlayerStartSpec` in
 * `hub_session.dart` (`onStarted`/`onDrained`). A `sessionId` mismatch against
 * the Dart-side active player is dropped by the caller, same fencing as
 * `PhoneMicFlutterApi`.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class StreamingPcmPlayerFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by StreamingPcmPlayerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      StreamingPcmPlayerPigeonPigeonCodec()
    }
  }
  /**
   * Fires once, the first time audio actually reaches the AudioTrack after
   * `start()` (i.e. on the first non-empty `enqueuePcm16`) — not at `start()`
   * itself, which only means "ready to receive", not "audibly speaking".
   */
  fun onStarted(sessionIdArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerFlutterApi.onStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(StreamingPcmPlayerPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(StreamingPcmPlayerPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Fires once per `flush()`, once the audio queued at that flush has had
   * time to actually leave the speaker. NOT driven by
   * `AudioTrack.setNotificationMarkerPosition` — whether that API's frame
   * position resets across a barge-in `pause()`+`flush()` cycle could not be
   * verified against real hardware in the environment this was written in
   * (see `StreamingPcmPlayer.bufferDrainMs` doc), so this is instead a fixed
   * post-roll delay after the native writer's software queue empties,
   * deliberately rounded up. A `clear()` before that delay elapses cancels
   * the pending callback — barge-in does not get a stray `onDrained` for
   * audio it just discarded.
   */
  fun onDrained(sessionIdArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerFlutterApi.onDrained$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(StreamingPcmPlayerPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(StreamingPcmPlayerPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Fires once when the app permanently loses audio focus while this
   * session's player is live (another app started its own playback/call, or
   * the OS handed focus to an incoming phone call — see native
   * `AudioFocusPolicy.actionFor`'s STOP case). By the time this arrives the
   * native side has already cleared the AudioTrack and abandoned the focus
   * request; Dart-side (`BaseHubSession._openConnection`'s
   * `VoicePlayerStartSpec.onAudioFocusLost`) treats it as a non-retryable
   * session error, same path as a fatal socket drop. A merely transient/
   * duckable loss does NOT reach Dart at all — the native side handles
   * those itself by lowering/restoring `AudioTrack` volume.
   */
  fun onAudioFocusLost(sessionIdArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_streaming_pcm_player.StreamingPcmPlayerFlutterApi.onAudioFocusLost$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(StreamingPcmPlayerPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(StreamingPcmPlayerPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
