// GENERATED by bridge/tools/gen_progress_phrases.py — НЕ править руками.
// Голос Charon, модель gemini-2.5-flash-preview-tts; тексты — bridge/tools/progress_phrases.json.
//
// Карта «тип активности -> озвученные фразы» для ProgressVoice (earcon.dart)
// и ProgressPhraseBank (progress_phrases.dart).
import 'progress_phrases.dart';

const Map<ClaudeActivity, List<ProgressPhrase>> progressPhraseAssets = {
  ClaudeActivity.think: [
    ProgressPhrase('assets/sounds/progress/think_1.mp3', 'Думаю над этим.'),
    ProgressPhrase('assets/sounds/progress/think_2.mp3', 'Секунду, анализирую.'),
    ProgressPhrase('assets/sounds/progress/think_3.mp3', 'Так, прикидываю варианты.'),
    ProgressPhrase('assets/sounds/progress/think_4.mp3', 'Размышляю, сейчас.'),
  ],
  ClaudeActivity.search: [
    ProgressPhrase('assets/sounds/progress/search_1.mp3', 'Ищу в файлах.'),
    ProgressPhrase('assets/sounds/progress/search_3.mp3', 'Смотрю, где это лежит.'),
    ProgressPhrase('assets/sounds/progress/search_4.mp3', 'Ищу по проекту.'),
  ],
  ClaudeActivity.read: [
    ProgressPhrase('assets/sounds/progress/read_3.mp3', 'Смотрю содержимое файла.'),
  ],
  ClaudeActivity.run: [
  ],
  ClaudeActivity.edit: [
  ],
  ClaudeActivity.web: [
  ],
  ClaudeActivity.memory: [
    ProgressPhrase('assets/sounds/progress/memory_1.mp3', 'Заглядываю в память.'),
  ],
  ClaudeActivity.agents: [
  ],
  ClaudeActivity.finishing: [
  ],
  ClaudeActivity.generic: [
  ],
};
